### ISSUE TITLE
🐞[BUG] - ㅋㅋ

### ISSUE THREAD

**Issue by HWANBINYOO** [Secu-Priate-Crew/Secu_Priate_Algorithm#1]
## 🐞어떤 버그인가요?
최준성
> 어떤 버그인지 간결하게 설명해주세요
최준성은 벌레입니다
## 🧐어떤 상황에서 발생한 버그인가요?
조선대에서
> (가능하면) Given-When-Then 형식으로 서술해주세요

## 🤔예상 결과

> 예상했던 정상적인 결과가 어떤 것이었는지 설명해주세요

**Comment by Jastes** [comment]
아가리 해주세요 ㅠㅠ
